image: muze/phantomjs:v2latest

unittest:
  before_script:
    - apt-get -qq -o Acquire::http::Proxy=${APTPROXY} update
    - apt-get -qq -o Acquire::http::Proxy=${APTPROXY} --no-install-recommends -y install git
    - git clone https://gitlab.muze.nl/muze/simply-test-store.git /tmp/simply-test-store
    - ( php -S 0.0.0.0:80  & )
    - ( cd /tmp/simply-test-store ; bash server.sh )
  script:
     - phantomjs tests/runner.js http://localhost/tests/data-display/ci.html
     - phantomjs tests/runner.js http://localhost/tests/data-edit/ci.html
  tags:
    - docker
  stage: test

syntaxtest:
  before_script:
    - npm -g install jshint
    - npm -g install csslint
  script:
    - jshint $(find js simply  -name \*.js | grep -v -E '^(simply/slip.js|simply/scripts.js)$')
    - csslint .
  tags:
    - docker
  stage: test

canary:
  stage: deploy
  environment: canary
  image: muze/deployer:latest
  when: on_success
  only:
    - master
    - /^master-[0-9]+$/
    - feature/deployer
  tags:
    - docker
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && /bin/echo -e "Host *.dc.muze.nl backup1.intern.muze.nl backup2.intern.muze.nl \n\tProxyCommand ssh muze-fundaments-jump nc -w 120 %h %p 2> /dev/null\n\tForwardAgent yes\t\n\nHost muze-fundaments-jump\n\tHostname shell.muze.nl\n\tUser deployer\n\tControlMaster auto\n\tControlPath ~/.ssh/master-%l-%r@%h:%p\n\tAddressFamily inet\n\tControlPersist 3600\n\n" > ~/.ssh/config'
    - composer --working-dir=.deploy/ install --no-scripts
    - 'NEXT=$(git for-each-ref  --format="%(refname:short)" **/origin/master-* | sort | tr -d -c "[:digit:]\n" | sort -nr | head -n1)'
    - 'NEXT=$((${NEXT:=-1}+1))'
    - 'if [ "${CI_BUILD_REF_NAME}" == "feature/deployer" ] ; then export MAJOR=${NEXT} ; else export MAJOR=$(echo "${CI_BUILD_REF_NAME}" | tr -d -c "[:digit:]" ) ; fi '
  script:
    - dep --file=.deploy/deploy.php -vv deploy
