image: muze/phantomjs:v4

before_script:
  - apt-get update
  - apt-get -qq -y install 
  - npm -g install jslint
  - git clone https://gitlab.muze.nl/muze/simply-test-store.git /tmp/simply-test-store
  - ( php -S 0.0.0.0:80  & )
  - ( cd /tmp/simply-test-store ; bash server.sh )

job1:
  script:
     - phantomjs tests/runner.js http://localhost/tests/data-edit/index.html
     - phantomjs tests/runner.js http://localhost/tests/data-display/index.html
  only:
    - ci
  tags:
    - docker
