image: muze/phantomjs:v4

before_script:
  - apt-get update
  - apt-get -qq --no-install-recommends -y install git
  - npm -g install jshint
  - git clone https://gitlab.muze.nl/muze/simply-test-store.git /tmp/simply-test-store
  - ( php -S 0.0.0.0:80  & )
  - ( cd /tmp/simply-test-store ; bash server.sh )

job1:
  script:
     - phantomjs tests/runner.js http://localhost/tests/data-display/index.html
     - phantomjs tests/runner.js http://localhost/tests/data-edit/index.html
     - jshint $(find js simply  -name \*.js)
  only:
    - ci
  tags:
    - docker
