image: cmfatih/phantomjs:latest

before_script:
  - echo 'deb http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu precise main'| tee /etc/apt/sources.d/php.list
  - apt-get update
  - apt-get -qq -y install git php5-cli
  - git clone https://gitlab.muze.nl/muze/simply-test-store.git /tmp/simply-test-store
  - cd /tmp/simply-test-store ; bash server.sh

stages:
  - test

job1:
  stage: test
  script:
    - phantomjs2 tests/data-display/run-tests.js
  only:
    - ci
  tags:
    - docker
