image: muze/phantomjs:latest

before_script:
  - apt-get update
  - apt-get -qq -y install git php5-cli
  - git clone https://gitlab.muze.nl/muze/simply-test-store.git /tmp/simply-test-store
  - ( cd /tmp/simply-test-store ; bash server.sh )
  - ls -la
  - pwd
  - whoami

stages:
  - test

job1:
  stage: test
  script:
    - phantomjs2 tests/data-display/run-tests.js
  only:
    - ci
  tags:
    - docker
