image: cmfatih/phantomjs:latest

before_script:
  - apt-get -qq -y install git php5-cli
  - git clone https://gitlab.muze.nl/muze/simply-test-store.git /tmp/simply-test-store
  - cd /tmp/simply-test-store ; bash server.sh

stages:
  - test

job1:
  stage: test
  script:
    - /bin/false
  only:
    - ci
  tags:
    - docker
