image: muze/phantomjs:latest

unittest:
  before_script:
    - apt-get -qq -o Acquire::http::Proxy=${APTPROXY} update
    - apt-get -qq -o Acquire::http::Proxy=${APTPROXY} --no-install-recommends -y install git
    - git clone https://gitlab.muze.nl/muze/simply-test-store.git /tmp/simply-test-store
    - ( php -S 0.0.0.0:80  & )
    - ( cd /tmp/simply-test-store ; bash server.sh )
  script:
     - phantomjs tests/runner.js http://localhost/tests/data-display/ci.html
     - phantomjs tests/runner.js http://localhost/tests/data-edit/ci.html
  tags:
    - docker

syntaxtest:
  before_script:
    - apt-get -qq -o Acquire::http::Proxy=${APTPROXY} update
    - apt-get -qq -o Acquire::http::Proxy=${APTPROXY} --no-install-recommends -y install nodejs-legacy
    - npm -g install jshint
    - npm -g install csslint
  script:
    - jshint $(find js simply  -name \*.js | grep -v -E '^(simply/slip.js|simply/scripts.js)$')
    - csslint .
  tags:
    - docker

